module.exports =  {
  products: [
    {
      _id: '1',
      name: 'Full Zip Runnig Shirt',
      category: 'Shirst',
      image: '/images/product-1.jpg',
      price: 119,
      brand: 'Nike',
      rating: 5,
      numReviews: 60,
      countInStock: 6,
    },
    {
      _id: '2',
      name: 'Nike Full Zip Hoodie Mens Workout Sweatshirt',
      category: 'Shirst',
      image: '/images/product-2.jpg',
      price: 60,
      brand: 'Hiskwin',
      rating: 5,
      numReviews: 10,
    },
    {
      _id: '3',
      name: 'Adidas Mens Long Sleeve Hoodie',
      category: 'Shirts',
      image: '/images/product-3.jpg',
      price: 60,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 10,
    },
    {
      _id: '4',
      name: 'Under Armour Mens Sportstyle Tricot Joggers',
      category: 'Under Armour',
      image: '/images/product-4.jpg',
      price: 0,
      brand: 'Hiskwin',
      rating: 4.5,
      numReviews: 10,
    },
    {
      _id: '5',
      name: 'Champion Mens Graphic Powerblend Fleece Jogger',
      category: 'Pants',
      image: '/images/product-5.jpg',
      price: 119,
      brand: 'Champion',
      rating: 3.5,
      numReviews: 198,
    },
    {
      _id: '6',
      name: 'Aelfric Eden Mens Joggers Panst Long Multi-Pockets',
      category: 'pants',
      image: '/images/product-6.jpg',
      price: 85,
      brand: 'Aelfric Eden',
      rating: 4.5,
      numReviews: 45,
      countInStock: 6,
    },
  ],
};
